### PR TITLE
Adding TMB analysis to the report

### PR DESCRIPTION
**Pull request by skanwal**

### CODE REVIEW

**Comment by pdiakumis** [comment]
Sehrish, thanks for this.
A few things to consider for getting it past Travis first:

* Have you tested the report locally first? Did it work fine? If yes, try also doing so with the VCF in https://github.com/umccr/umccrise_test_data/blob/master/gold_standard/bcbio_test_project/work/cup__cup_tissue/rmd/ensemble-with_chr_prefix.vcf, since that's the one that gets tested with Travis. Does this VCF make sense to get tested with your code, since the chromosomes have the 'chr' prefix?

Further:

* Which VCF file in the umccrise output does your code intend to run on? We'll need to make sure we're using the correct VCF. We might have to add an additional parameter in there.

Cheers - Peter

**Comment by vladsaveliev** [comment]
Hmm, travis error because `rock` failed to install.

```
> library(devtools) ; options(unzip = '/usr/bin/unzip') ; devtools::install_github('umccr/rock', ref = 'umccrise')
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Downloading GitHub repo umccr/rock@umccrise
from URL https://api.github.com/repos/umccr/rock/zipball/umccrise
Installing rock
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
trying URL 'https://cran.rstudio.com/src/contrib/gtools_3.8.1.tar.gz'
Content type 'application/x-gzip' length 187516 bytes (183 KB)
==================================================
downloaded 183 KB
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Installation failed: error in running command
trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.2.2.tar.gz'
Content type 'application/x-gzip' length 325128 bytes (317 KB)
==================================================
downloaded 317 KB
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Installation failed: error in running command
trying URL 'https://cran.rstudio.com/src/contrib/vcfR_1.8.0.tar.gz'
Content type 'application/x-gzip' length 1415019 bytes (1.3 MB)
==================================================
downloaded 1.3 MB
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Installation failed: error in running command
Downloading GitHub repo umccr/pebbles@master
from URL https://api.github.com/repos/umccr/pebbles/zipball/master
Installing pebbles
'/home/travis/miniconda/envs/umccrise/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmpjsrs4V/devtools1bbc2a032be4/umccr-pebbles-3306fea'  \
  --library='/home/travis/miniconda/envs/umccrise/lib/R/library'  \
  --install-tests 
* installing *source* package ‘pebbles’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (pebbles)
'/home/travis/miniconda/envs/umccrise/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmpjsrs4V/devtools1bbc52be3cf9/umccr-rock-ed7712a'  \
  --library='/home/travis/miniconda/envs/umccrise/lib/R/library'  \
  --install-tests 
ERROR: dependency ‘gtools’ is not available for package ‘rock’
* removing ‘/home/travis/miniconda/envs/umccrise/lib/R/library/rock’
Installation failed: Command failed (1)
Warning messages:
1: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘/bin/gtar -xf '/tmp/Rtmpjsrs4V/gtools_3.8.1.tar.gz' -C '/tmp/Rtmpjsrs4V/devtools1bbc6ce92c8b'’ returned error code 127
2: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘/bin/gtar -xf '/tmp/Rtmpjsrs4V/rlang_0.2.2.tar.gz' -C '/tmp/Rtmpjsrs4V/devtools1bbc3547197e'’ returned error code 127
3: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘/bin/gtar -xf '/tmp/Rtmpjsrs4V/vcfR_1.8.0.tar.gz' -C '/tmp/Rtmpjsrs4V/devtools1bbc1533779d'’ returned error code 127
> 
> 
```

**Comment by vladsaveliev** [comment]
Should probably add something like `options(gtar = '/use/bin/gtar')`, though not sure why it worked before

**Comment by pdiakumis** [comment]
Ah, I've just pushed a fix for that one (I had a gtools pkg dependency which I got rid of). Might need to fix my PR first, then we'll fix Sehrish's. Coming now.

**Comment by skanwal** [comment]
Thanks, Peter and Vlad.

1. @pdiakumis the code works fine with the VCF you have pointed out.
2. If I remember correctly, we had agreed to use vcf that is used as an input for PCGR?

**Comment by vladsaveliev** [comment]
Looks like tests are passing, so merging. Thanks Sehrish and Peter.

**Comment by skanwal** [comment]
Yay! Thanks Vlad and Peter.

**Pull request merged**
