### PR TITLE
Pin pandoc and update MultiQC

### PR DESCRIPTION
**Pull request by pdiakumis**
Solves #84 and #85.

### CODE REVIEW

**Review by scwatts — APPROVED** [review]
LGTM, thanks for resolving.

**Comment by scwatts** [comment]
Noticed the merge target is `bcbio_v1.2.4` - another branch or branch name might be more appropriate here. Perhaps using `bcbio` as branch name and then tagging with `bcbio_v1.2.4` or `bcbio_v1.2.5` etc is more suitable.

Changing tagging format as above may require adjustments to the codebuild stack as it probably violates semver. Other tagging schemes could be used in place, depending if we chose that route.

**Comment by pdiakumis** [comment]
Don't think branch name/tag really matters in this case - we're not planning on updating the AWS production release. This is mainly for testing on Gadi, which will become obsolete soon. Let me merge this and then I'll rename the branch to bcbio and bump the version to 1.2.5.

**Comment by scwatts** [comment]
Renaming the branch but retaining version tag format helps cleans things up sufficient I think.

**Pull request merged**
