### PR TITLE
Deployment enhancement and cleanup/conditioning

### PR DESCRIPTION
**Pull request by brainstorm**
[AMI being built with this branch/PR for now](https://travis-ci.org/umccr/umccrise-ami), until those changes get merged upstream.

* Adds Ansible deployment roles to be able to deploy multi-cloud as well as locally via vagrant.
* Uses svtools bioconda package instead of `scripts/VcfToBedPe` one-off. More cleaning to come.

### CODE REVIEW

**Comment by brainstorm** [comment]
The build is breaking because of `svtools`, most probably:

https://github.com/bioconda/bioconda-recipes/pull/4361

Care to fix it well and upstream? :)

**Comment by vladsaveliev** [comment]
Yep, see that, will fix

**Comment by vladsaveliev** [comment]
Hmm, not really sure which dependency is using svtools

**Comment by vladsaveliev** [comment]
Who's Andrew Rothstein?

**Comment by vladsaveliev** [comment]
`svtools` is py2.7 only. That's why I didn't use the conda package. You should have asked first. Care to port it fully to py3? ;)

**Comment by vladsaveliev** [comment]
But I really appreciate that you reviewed the code. This is fantastic, honestly. If you have more concerns, let me know your thoughts or create an issue

**Comment by vladsaveliev** [comment]
Awesome, thanks!

What do you mean by vendor? Is it a section in setup.py? Happy to do the right way

**Comment by vladsaveliev** [comment]
And I still owe you a umccrise conda package, right?

I was lost in that R dependency hell while making it

**Comment by vladsaveliev** [comment]
It'll fail because of removed `params` sections: https://github.com/umccr/umccrise/pull/6/commits/12f5dcb063864a6f0df8d54c76ed24ee5a9018ef

Need to edit the shell lines as well:

```
  'cat {input.bed} | {params.vcftobedpe}'
```

to

```
  'cat {input.bed} | vcfToBedpe'
```

**Comment by brainstorm** [comment]
See this SO accepted answer for the vendor thing, standard python project structure, also true for i.e ruby and other languages/projects:

https://stackoverflow.com/questions/18812614/embedding-a-python-library-in-my-own-package

**Comment by brainstorm** [comment]
Don't worry about the package, I'll just deploy it as-is.

**Comment by vladsaveliev** [comment]
Ah, so just make a folder `vendor` in the root of the project, gotha

**Comment by vladsaveliev** [comment]
Yay!

**Comment by brainstorm** [comment]
Uh, that was a tad too fast, I'm getting some weird errors still with the local Vagrant deploy, not sure if the packer one will complete at all, tbh, but let's keep an eye on it:

https://travis-ci.org/umccr/umccrise-ami

**Comment by vladsaveliev** [comment]
Ah, should have let you merge :D

**Pull request merged**
